name: Node.js CI

on: [push]

jobs:

  lint-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install commitlint
        run: |
          npm install -g @commitlint/config-conventional

      - name: Validate current commit lint
        run: git log -1 --pretty=format:"%s" | npx commitlint